### ISSUE TITLE
[Query] - NextJS

### ISSUE THREAD

**Issue by ilavenilp** [mcnamee/react-starter-kit#2]
Hello McNamee,
            Do you think, we should be able to acheive the features given by Next JS framework?
I am searching for reasons to get rid of NextJS. Could you help?

thanks

**Comment by mcnamee** [comment]
Hi @karka86 
I think one of big draw cards to NextJS, is that it offers SSR (server side rendering). Of course, this means that you need to run a node server, so may not be suitable for all use cases.

My opinion is that if you need SSR in your project, NextJS is a great option. However if a SPA (single page app) is the right tool for the project, a client side rendered React app like https://github.com/mcnamee/react-starter-kit is perfect.
